version: '2'

services:
  sickchill:
    image: sickchill/sickchill:master
    container_name: sickchill
    ports:
      - 32481:8081
    volumes:
      - /srv/sickchill/data:/data
      - /srv/sickchill/downloads:/downloads
      - /srv/sickchill/tv:/tv
      - /srv/sickchill/cache:/app/sickchill/sickchill/gui/slick/cache
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.sickchill_http.rule=Host(`sickchill.zz`) || Host(`sick.zz`)
      - traefik.http.routers.sickchill_http.entrypoints=web
      - traefik.http.routers.sickchill_http.service=sickchill
      - traefik.http.services.sickchill.loadbalancer.server.port=8081

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: docker
    network_mode: host
    volumes:
      - /home/kpi/extra/media/kate:/kate
      - /srv/sickchill/tv:/sickchill/tv
      - /srv/sickchill/downloads:/sickchill/downloads
      - /srv/youtubedl:/youtubedl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex_http.rule=Host(`plex.zz`)"
      - "traefik.http.routers.plex_http.entrypoints=web"
      - "traefik.http.services.plex_http.loadbalancer.server.port=32400"
#    ports:
#      - 32400:32400

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=32480
    volumes:
      - /srv/qbittorrent/config:/config
      - /srv/sickchill/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.torrent_http.rule=Host(`torrent.zz`)"
      - "traefik.http.routers.torrent_http.entrypoints=web"
      - traefik.http.services.torrent_http.loadbalancer.server.port=32480
    ports:
      - 32480:32480
      - 32881:6881
      - 32881:6881/udp
